# -*- coding: utf-8 -*-
"""
配置模块初始化文件
提供配置的统一访问接口
"""

# ==================== 导入所有配置 ====================
# 路径配置
from .paths import (
    ROOT_DIR, DATA_DIR, CACHE_DIR, TEMP_DIR,
    OUTPUT_DIR, IMAGES_DIR, OUTPUT_DATA_DIR,
    UTILS_DIR, SRC_DIR, SCRIPT_DIR, TESTS_DIR,
    SUPPORTED_IMAGE_FORMATS, SUPPORTED_DATA_FORMATS,
    DEFAULT_IMAGE_FORMAT, DEFAULT_DATA_FORMAT
)

# 数据字段映射配置
from .data_mapping import (
    DEFAULT_FIELD_MAPPING, CURRENT_DATA_SOURCE
)

# 数据处理配置
from .data_processing import (
    GLOBAL_DATA_PROCESSING_CONFIG, DATA_PREPROCESSING_CONFIG,
    DATA_PROCESSING_CONFIG
)

# 特征工程配置
from .features import (
    FEATURE_ENGINEERING_CONFIG, DATA_TRANSFORMATION_CONFIG
)

# ARIMA模型配置
from .arima_config import (
    ARIMA_TRAINING_CONFIG, ARIMA_OUTPUT_CONFIG, ARIMA_SEASONALITY_CONFIG,
    ARIMA_OPTIMIZATION_CONFIG, ARIMA_VISUALIZATION_CONFIG, ARIMA_DATA_PREPROCESSING_CONFIG
)

# Prophet模型配置
from .prophet_config import (
    PROPHET_TRAINING_CONFIG, PROPHET_DEFAULT_PARAMS, PROPHET_PARAM_GRID
)

# 功能模块配置
from .modules import (
    BASIC_ANALYSIS_CONFIG, DATA_PREPROCESSING_CONFIG as MODULE_DATA_PREPROCESSING_CONFIG,
    ARIMA_PREDICTION_CONFIG, CLASSICAL_DECOMPOSITION_PREDICTION_CONFIG
)

# ==================== 配置导出 ====================
__all__ = [
    # 路径配置
    'ROOT_DIR', 'DATA_DIR', 'CACHE_DIR', 'TEMP_DIR',
    'OUTPUT_DIR', 'IMAGES_DIR', 'OUTPUT_DATA_DIR',
    'UTILS_DIR', 'SRC_DIR', 'SCRIPT_DIR', 'TESTS_DIR',
    'SUPPORTED_IMAGE_FORMATS', 'SUPPORTED_DATA_FORMATS',
    'DEFAULT_IMAGE_FORMAT', 'DEFAULT_DATA_FORMAT',
    
    # 数据字段映射配置
    'DEFAULT_FIELD_MAPPING', 'CURRENT_DATA_SOURCE',
    
    # 数据处理配置
    'GLOBAL_DATA_PROCESSING_CONFIG', 'DATA_PREPROCESSING_CONFIG',
    'DATA_PROCESSING_CONFIG',
    
    # 特征工程配置
    'FEATURE_ENGINEERING_CONFIG', 'DATA_TRANSFORMATION_CONFIG',
    
    # ARIMA模型配置
    'ARIMA_TRAINING_CONFIG', 'ARIMA_OUTPUT_CONFIG', 'ARIMA_SEASONALITY_CONFIG',
    'ARIMA_OPTIMIZATION_CONFIG', 'ARIMA_VISUALIZATION_CONFIG', 'ARIMA_DATA_PREPROCESSING_CONFIG',
    
    # Prophet模型配置
    'PROPHET_TRAINING_CONFIG', 'PROPHET_DEFAULT_PARAMS', 'PROPHET_PARAM_GRID',
    
    # 功能模块配置
    'BASIC_ANALYSIS_CONFIG', 'MODULE_DATA_PREPROCESSING_CONFIG',
    'ARIMA_PREDICTION_CONFIG', 'CLASSICAL_DECOMPOSITION_PREDICTION_CONFIG'
] 